### ISSUE TITLE
Polygon Grant Hackathon - Unmarshal Bounties

### ISSUE THREAD

**Issue by Nishanth-s-r** [eucrypt/unmarshal-bounty#4]
Unmarshal would want the participants to explore as much as they can with Unmarshal APIs and hence we have decided to come with 3 bounties. 
Participants can try their hand at multiple bounties. 
The best 3 solutions will be awarded . Please find below the details of Unmarshal Bounties for Hackathon

**Bounty: 1** 

**_Whale Alerts:_** 

Using Unmarshal’s notification Engine as a base we would want the bounty hunters to build a whale alert system that alerts when a huge buy or a huge sell happens on a particular token or a particular chain. 

You can use any means of notifications Chrome Notifications, Firebase or Apps.

The details the team could put in alerts and the different varieties of alerts that could be produced will see weightage in assessing the bounty. 

-------------------------------------------------------------------------------

**Bounty 2:**

**_NFT Marketplace Framework :_**

With the Unmarshal NFT APIs  in use, we would like the bounty hunters to come up with something like a NFT marketplace on multichain(Unmarshal currently supports Eth & BSC) where users can view, display , buy or sell NFT. 

Another option here would be to set up an NFT portfolio page using Unmarshal NFT APIs. 
The portfolio should give as much details as possible related to all NFT held in a wallet. 

-------------------------------------------------------------------------------------

**Bounty 3:**

**_Telegram Bot:_**

We are looking for someone who could create telegram bots for us using our APIs. For example if someone types in  /(walletaddress):bsc the bot should use our APIs to fetch all the asset balances on the BSC chain in the wallet address. 

This is just an example. 
We are looking at creative bots that can fetch as much details as possible from our APIs
-----------------------------------------------------------------------------------------

Refer to https://docs.unmarshal.io for the list of all Unmarshal APIs. 
The project with maximum utilisations of Unmarshal APIs will stand a chance at winning the bounty.  

You can reach out to support@unmarshal.io for any queries

------------------------------------------------------------------------------------------

_**Bounty prizes worth $3,000 up for grabs.**_

**Comment by sonny2k** [comment]
Is this still open? The bounty appears to be closed on Hackerlink

**Comment by Nishanth-s-r** [comment]
Hi,

The bounty will be re published soon

**Comment by Nishanth-s-r** [comment]
Hello,

Apologies for the confusion.. the bounty will be back soon..

**Comment by Nishanth-s-r** [comment]
Closing this and creating 3 separate tickets for the bounties.
